import { ACTION, PERMISSION } from '@/consts/permissions'

export default [
  {
    title: 'Painel Inicial',
    route: 'home',
    icon: 'grid_view',
    order: 10,
    resource: PERMISSION.GENERAL.TEACHER,
    action: ACTION.READ,
  },
  {
    title: 'Missões da Escola',
    icon: 'flag',
    order: 20,
    children: [
      {
        title: 'Criar Missão',
        route: 'newMissionsTeacher',
        resource: PERMISSION.MODULE.SCHOOL_MISSIONS,
        action: ACTION.READ,
      },
      {
        title: 'Missões',
        route: 'activeMissions',
        resource: PERMISSION.MODULE.SCHOOL_MISSIONS,
        action: ACTION.READ,
      },
      /*  {
        title: 'Missões Plus',
        route: 'activeMissionsPlus',
        resource: PERMISSION.MODULE.CUSTOM_MISSIONS_PLUS,
        action: ACTION.READ,
      }, */
      // {
      //   title: 'Ranking de Conquistas',
      //   route: 'TeacherSchoolRanking',
      //   resource: PERMISSION.MODULE.SCHOOL_MISSIONS_ACHIEVEMENT_RANKING,
      //   action: ACTION.READ,
      // },
    ],
  },
  {
    title: 'generalReports',
    icon: 'pie_chart',
    order: 30,
    children: [
      {
        title: 'Relatório de Evidências',
        route: 'TeacherEvidenceReport',
        resource: PERMISSION.MODULE.REPORTS,
        action: ACTION.READ,
      },
      {
        title: 'Habilidades',
        route: 'TeacherSkillReport',
        resource: PERMISSION.MODULE.REPORTS,
        action: ACTION.READ,
      },
      {
        title: 'Acesso dos Alunos',
        route: 'studentAccess',
        resource: PERMISSION.MODULE.REPORTS,
        action: ACTION.READ,
      },
    ],
  },
  {
    title: 'Explorar Jogos',
    icon: 'map',
    order: 40,
    children: [
      {
        title: 'Configurações da Ilha',
        route: 'TeacherExploreGamesConfiguration',
        resource: PERMISSION.MODULE.ISLANDS,
        action: ACTION.READ,
      },
      {
        title: 'Ranking de Conquistas',
        route: 'TeacherIslandSchoolRanking',
        resource: PERMISSION.MODULE.ISLANDS_ACHIEVEMENT_RANKING,
        action: ACTION.READ,
      },
    ],
  },
  {
    title: 'Turmas',
    icon: 'work_outline',
    route: 'teacherClasses',
    order: 50,
    resource: PERMISSION.GENERAL.TEACHER,
    action: ACTION.READ,
  },
  {
    title: 'Grupos',
    icon: 'groups',
    route: 'GroupsList',
    order: 55,
    resource: PERMISSION.GENERAL.CLASS_GROUP,
    action: ACTION.READ,
  },
  {
    title: 'Alunos',
    icon: 'group',
    route: 'teacherStudents',
    order: 60,
    resource: PERMISSION.GENERAL.TEACHER,
    action: ACTION.READ,
  },
  {
    title: 'Avaliações',
    icon: 'quiz',
    order: 76,
    children: [
      {
        title: 'Complexidade Narrativa',
        route: 'narrativeComplexityStudents',
        resource: PERMISSION.MODULE.NARRATIVECOMPLEXITY,
        action: ACTION.READ,
      },
      {
        title: 'Fases da Escrita',
        route: 'WritingPhasesList',
        resource: PERMISSION.MODULE.WRITING_STAGES,
        action: ACTION.READ,
      },
      {
        title: 'Fluência Leitora',
        route: 'readingMeterClassesOverview',
        resource: PERMISSION.MODULE.READINGFLUENCY,
        action: ACTION.READ,
      },
      {
        title: 'Fluência Leitora',
        route: 'TeacherFluencyV2Evaluations',
        resource: PERMISSION.MODULE.READING_FLUENCY_EVALUATION,
        action: ACTION.READ,
      },
      {
        title: 'Avaliação Digital',
        route: 'evaluationsTeacher',
        resource: PERMISSION.MODULE.EVALUATIONS,
        action: ACTION.READ,
      },
      {
        title: 'Simulados',
        route: 'redirectSimulationsUrl',
        resource: PERMISSION.MODULE.EVOLUCIIONAL_SIMULATIONS,
        action: ACTION.READ,
      },
    ],
  },
  {
    title: 'Expedição Leitura',
    icon: 'book_5',
    route: 'readingExpeditionOverview',
    order: 76,
    resource: PERMISSION.MODULE.READING_EXPEDITION,
    action: ACTION.READ,
  },
  {
    title: 'Eventos',
    icon: 'calendar_today',
    route: 'teacherEvents',
    order: 80,
    resource: PERMISSION.MODULE.EVENTS,
    action: ACTION.READ,
  },
  {
    title: 'High Five',
    icon: 'camera',
    route: 'teacherHighFive',
    order: 85,
    resource: PERMISSION.MODULE.HIGH_FIVE,
    action: ACTION.READ,
  },
  {
    title: 'Ajudas e Materiais',
    route: 'supportMaterials',
    icon: 'file_download',
    order: 90,
    resource: PERMISSION.GENERAL.SUPPORT_MATERIALS,
    action: ACTION.READ,
  },
  {
    title: 'Educateca',
    icon: 'screen_search_desktop',
    route: 'MeetGames',
    order: 100,
    resource: PERMISSION.GENERAL.TEACHER,
    action: ACTION.READ,
  },
]
