/**
 * TabRouter - Tabs with Vue Router Integration
 */

export default {
  title: 'Educacross Components V2/Navigation/TabRouter',
  tags: ['autodocs']
};

const styles = `<style>
.tab-router{border-bottom:1px solid #E8E8E8}.tab-router-list{display:flex;gap:4px;list-style:none;margin:0;padding:0}.tab-router-item{position:relative}.tab-router-link{display:flex;align-items:center;gap:8px;padding:14px 20px;color:#6E6B7B;text-decoration:none;font-size:15px;font-weight:500;border-bottom:2px solid transparent;transition:all .2s;cursor:pointer}.tab-router-link:hover{color:#6E63E8;background:#F8F8F8}.tab-router-link.active{color:#6E63E8;border-bottom-color:#6E63E8}.tab-router-link i{font-size:18px}.tab-badge{background:#EA5455;color:#fff;font-size:11px;font-weight:600;padding:2px 6px;border-radius:10px;min-width:18px;text-align:center}.tab-router.pills .tab-router-link{border-radius:6px;border-bottom:none}.tab-router.pills .tab-router-link.active{background:#6E63E8;color:#fff}
</style>`;

const routes=[{path:'/dashboard',label:'Dashboard',icon:'bi-speedometer2'},{path:'/missions',label:'Missões',icon:'bi-book',badge:5},{path:'/students',label:'Alunos',icon:'bi-people'},{path:'/reports',label:'Relatórios',icon:'bi-bar-chart'}];

export const Default={render:()=>`${styles}<nav class="tab-router"><ul class="tab-router-list">${routes.map((r,i)=>`<li class="tab-router-item"><a href="#${r.path}" class="tab-router-link ${i===0?'active':''}" onclick="event.preventDefault()"><i class="bi ${r.icon}"></i><span>${r.label}</span>${r.badge?`<span class="tab-badge">${r.badge}</span>`:''}</a></li>`).join('')}</ul></nav><p style="margin-top:16px;font-size:13px;color:#6E6B7B"><strong>Contexto:</strong> Navegação principal do dashboard do professor.</p>`};

export const WithIcons={render:()=>`${styles}<nav class="tab-router"><ul class="tab-router-list"><li class="tab-router-item"><a href="#" class="tab-router-link active"><i class="bi bi-grid"></i><span>Visão Geral</span></a></li><li class="tab-router-item"><a href="#" class="tab-router-link"><i class="bi bi-graph-up"></i><span>Desempenho</span></a></li><li class="tab-router-item"><a href="#" class="tab-router-link"><i class="bi bi-list-check"></i><span>Atividades</span><span class="tab-badge">12</span></a></li><li class="tab-router-item"><a href="#" class="tab-router-link"><i class="bi bi-clock-history"></i><span>Histórico</span></a></li></ul></nav>`};

export const PillsVariant={render:()=>`${styles}<nav class="tab-router pills"><ul class="tab-router-list">${routes.map((r,i)=>`<li class="tab-router-item"><a href="#" class="tab-router-link ${i===0?'active':''}"><i class="bi ${r.icon}"></i><span>${r.label}</span></a></li>`).join('')}</ul></nav><p style="margin-top:16px;font-size:13px;color:#6E6B7B"><strong>Variante:</strong> Pills com background colorido.</p>`};

export const PerfilDoAluno={render:()=>`${styles}<div style="max-width:800px"><div style="margin-bottom:20px;padding:20px;background:#fff;border:1px solid #D8D6DE;border-radius:8px 8px 0 0"><div style="display:flex;align-items:center;gap:16px"><div style="width:64px;height:64px;border-radius:50%;background:linear-gradient(135deg,#6E63E8,#28C76F);display:flex;align-items:center;justify-content:center;color:#fff;font-size:24px;font-weight:700">JS</div><div><h2 style="margin:0 0 4px;font-size:20px;font-weight:600;color:#5E5873">João Silva</h2><p style="margin:0;font-size:14px;color:#6E6B7B">5º A • Matrícula: 2024001234 • <span style="color:#28C76F">●</span> Ativo</p></div></div></div><nav class="tab-router"><ul class="tab-router-list"><li class="tab-router-item"><a href="#" class="tab-router-link active"><i class="bi bi-person"></i><span>Resumo</span></a></li><li class="tab-router-item"><a href="#" class="tab-router-link"><i class="bi bi-book"></i><span>Missões</span><span class="tab-badge">8</span></a></li><li class="tab-router-item"><a href="#" class="tab-router-link"><i class="bi bi-graph-up"></i><span>Desempenho</span></a></li><li class="tab-router-item"><a href="#" class="tab-router-link"><i class="bi bi-trophy"></i><span>Conquistas</span></a></li><li class="tab-router-item"><a href="#" class="tab-router-link"><i class="bi bi-clock-history"></i><span>Histórico</span></a></li></ul></nav></div><p style="margin-top:16px;font-size:13px;color:#6E6B7B"><strong>Contexto:</strong> Perfil do aluno com 5 seções navegáveis.</p>`};

export const RelatorioMissao={render:()=>`${styles}<div style="max-width:900px"><div style="margin-bottom:16px"><h2 style="margin:0 0 4px;font-size:20px;font-weight:600;color:#5E5873">Missão: Frações Básicas</h2><p style="margin:0;font-size:14px;color:#6E6B7B">5º A • Matemática • Aplicada em 15/01/2024</p></div><nav class="tab-router"><ul class="tab-router-list"><li class="tab-router-item"><a href="#" class="tab-router-link active"><i class="bi bi-grid"></i><span>Visão Geral</span></a></li><li class="tab-router-item"><a href="#" class="tab-router-link"><i class="bi bi-people"></i><span>Alunos</span><span class="tab-badge" style="background:#28C76F">28</span></a></li><li class="tab-router-item"><a href="#" class="tab-router-link"><i class="bi bi-list-ol"></i><span>Questões</span></a></li><li class="tab-router-item"><a href="#" class="tab-router-link"><i class="bi bi-file-earmark-text"></i><span>Evidências</span></a></li><li class="tab-router-item"><a href="#" class="tab-router-link"><i class="bi bi-download"></i><span>Exportar</span></a></li></ul></nav></div><p style="margin-top:16px;font-size:13px;color:#6E6B7B"><strong>Contexto:</strong> Relatório de missão com navegação.</p>`};

export const DashboardCoordenador={render:()=>`${styles}<div style="max-width:1200px"><div style="margin-bottom:20px"><h1 style="margin:0 0 4px;font-size:24px;font-weight:700;color:#5E5873">Painel do Coordenador</h1><p style="margin:0;font-size:14px;color:#6E6B7B">João Carlos • Escola Municipal Vista Alegre • 24 turmas, 32 professores</p></div><nav class="tab-router"><ul class="tab-router-list"><li class="tab-router-item"><a href="#" class="tab-router-link active"><i class="bi bi-speedometer2"></i><span>Dashboard</span></a></li><li class="tab-router-item"><a href="#" class="tab-router-link"><i class="bi bi-grid-3x3"></i><span>Turmas</span><span class="tab-badge" style="background:#6E63E8">24</span></a></li><li class="tab-router-item"><a href="#" class="tab-router-link"><i class="bi bi-person-badge"></i><span>Professores</span><span class="tab-badge" style="background:#6E63E8">32</span></a></li><li class="tab-router-item"><a href="#" class="tab-router-link"><i class="bi bi-graph-up-arrow"></i><span>Desempenho</span></a></li><li class="tab-router-item"><a href="#" class="tab-router-link"><i class="bi bi-file-bar-graph"></i><span>Relatórios</span></a></li><li class="tab-router-item"><a href="#" class="tab-router-link"><i class="bi bi-gear"></i><span>Configurações</span></a></li></ul></nav></div><p style="margin-top:16px;font-size:13px;color:#6E6B7B"><strong>Contexto:</strong> Dashboard coordenador - 6 seções principais.</p>`};

export const KeyboardNavigation={render:()=>`${styles}<style>.tab-router-link:focus{outline:2px solid #6E63E8;outline-offset:-2px}</style><nav class="tab-router"><ul class="tab-router-list" role="tablist">${routes.map((r,i)=>`<li class="tab-router-item" role="presentation"><a href="#" class="tab-router-link ${i===0?'active':''}" role="tab" tabindex="${i===0?'0':'-1'}" aria-selected="${i===0}"><i class="bi ${r.icon}"></i><span>${r.label}</span></a></li>`).join('')}</ul></nav><div style="margin-top:20px;padding:16px;background:#F8F8F8;border-radius:8px;font-size:13px;color:#6E6B7B"><strong>WCAG 2.1 AA:</strong><ul style="margin:8px 0 0;padding-left:20px"><li><kbd>←</kbd> <kbd>→</kbd> - Navegar entre tabs<li><kbd>Home</kbd> / <kbd>End</kbd><li><strong>role="tablist"</strong> + <strong>role="tab"</strong><li><strong>aria-selected</strong> indica tab ativa</ul></div>`};
