// No migration needed - keep as-is

export const blockClassRegs = [
  /\/teacher\/[\w-]+\/[0-9]+\/books\/[0-9]+/,
  /\/teacher\/[\w-]+\/[0-9]+\/reports\/[0-9]+/,
  /\/teacher\/[\w-]+\/[0-9]+\/missions\/[0-9]+/,
  /\/teacher\/reports\/missions/,
  /\/teacher\/highfive\/report/,
  /\/teacher\/reports\/highfive\/missions\/[0-9]+/,
  /\/teacher\/evaluations\/[0-9]+\/students/,
  /\/teacher\/evaluations\/[0-9]+\/result\/students/,
  /\/teacher\/evaluations\/[0-9]+\/result\/students\/analysis/,
  /\/teacher\/evaluations\/[0-9]+\/result\/students\/ability/,
  /\/teacher\/evaluations\/[0-9]+\/answerkey/,
  /\/teacher\/event\/[0-9]+/,
  /\/teacher\/dashboard\/followup\/[0-9]+/,
  /\/teacher\/events\/[0-9]+\/individual-report/,
  /\/teacher\/students\/[0-9]+\/details/,
  /\/reading-expedition\/units\/[0-9]+\/student\/[0-9]+/,
  /\/reading-expedition\/fluency-tests\/[0-9]+\/student\/[0-9]+/,
  /\/teacher\/missions-plus\/create/,
  /\/teacher\/missions-plus\/edit\/[0-9]+/,
  /\/teacher\/missions-plus\/report\/[0-9]+\/classe/,
  /\/teacher\/missions-plus\/report\/[0-9]+\/students/,
  /\/teacher\/missions-plus\/report\/[0-9]+\/ranking/,
  /\/teacher\/missions\/ranking/,
  /\/writing-phases\/[0-9]+/,
  /\/narrative-complexity\/student\/[0-9]+/,
  /\/reading-fluency-evaluation\/[0-9]+\/class\/[0-9]+/,
  /\/teacher\/reading-fluency-evaluation\/[0-9]+\/class\/[0-9]+\/student\/[0-9]+\/student-report/,
]

export const hideClassRegs = [
  /\/supportMaterials/,
  /\/teacher\/records\/classes/,
  /\/teacher\/custom-mission/,
  /\/groups\/create/,
  /\/groups\/edit\/[0-9]/,
  /\/teacher\/records\/students\/create/,
  /\/teacher\/records\/students\/create/,
  /\/teacher\/records\/students\/edit\/[0-9]+/,
  /\/teacher\/records\/students\/import/,
  /\/teacher\/records\/students\/importStudentsList/,
  /\/teacher\/records\/students\/listImportedStudents/,
  /\/teacher\/records\/students\/importStudentsView/,
  /\/teacher\/records\/students\/importStudentsResendEmail/,
  /\/teacher\/evaluations\/[0-9]+\/result\/students\/analysis\/[0-9]+/,
  /\/teacher\/reading-meter\/test\/[0-9]+/,
  /\/teacher\/reading-meter\/library\/[0-9]+/,
  /\/error-context/,
]