FROM node:22-alpine as build-stage

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Increase Node memory limit for Vite builds
ENV NODE_OPTIONS=--max-old-space-size=4096

ENV VITE_APP_BASE_URL_API=https://apimanager.educacross.com.br/
ENV VITE_APP_BLOB_IMAGE=https://blob.educacross.com.br/
ENV VITE_APP_BLOB=https://blob.educacross.com.br/
ENV VITE_APP_DEEPLINK_URL=https://account.educacross.com.br/
ENV VITE_APP_GOOGLE_CLIENT_ID=824777903381-oko0t2danlin33a8manp3l95i33c9qgg
ENV VITE_APP_LEX_CLIENT_ID=46d1077d3ce54acca86c0e70204c4ee2
ENV VITE_APP_LEX_LOGIN=https://api.lex.education/
ENV VITE_APP_LEX_REDIRECT=https://account.educacross.com.br/lex
ENV VITE_APP_LOGIN_LEX_PAGE=https://sso.lex.education/
ENV VITE_APP_LEX_MAPLE_CLIENT_ID=46d1077d3ce54acca86c0e70204c4ee2
ENV VITE_APP_LEX_MAPLE_LOGIN=https://apis.lex.education/
ENV VITE_APP_LEX_MAPLE_REDIRECT=https://account.educacross.com.br/lex-mbg
ENV VITE_APP_LOGIN_LEX_MAPLE_PAGE=https://accounts.lex.education/
ENV VITE_APP_LOGIN_SAS_PAGE=https://portalsaseducacao.com.br/login
ENV VITE_APP_MISSION_SUGGEST_URL=https://prod.empatie.net/
ENV VITE_APP_WEBGL_PLAY_LINK=https://www.educacross.link/jogar
ENV VITE_APP_WHITELABEL=educacross
ENV VITE_APP_PLURALL_LINK=https://sso.plurall.net/
ENV VITE_APP_PLURALL_REDIRECT=https://account.educacross.com.br/plurall
ENV VITE_APP_PLURALL_CLIENT_ID=NjMxXSRTxNzk0NDI2ZmIx
ENV VITE_APP_LOGIN_PLURALL_PAGE=https://login.plurall.net/
ENV VITE_APP_LOGIN_COC_PAGE=https://portal.coc.com.br/
ENV VITE_APP_LOGIN_POSITIVO_PAGE=https://positivoon.com.br/
ENV VITE_APP_REDIRECT_URI_MICROSOFT=https://account.educacross.com.br
ENV VITE_APP_LAYERS_LINK=https://id.layers.digital
ENV VITE_APP_LAYERS_REDIRECT=https://account.educacross.com.br/layers
ENV VITE_APP_LAYERS_CLIENT_ID=educacross
ENV VITE_APP_LOGIN_LAYERS_PAGE=https://layers.education
ENV VITE_APP_LOGIN_ARCO_SAS_PAGE_REDIRECT=https://app.portalsaseducacao.com.br/entrar/?appendOpaqueToken=true&redirect=https://account.educacross.com.br/sas?opaquetoken={{PARTNER_API_OPAQUE_TOKEN}}
ENV VITE_APP_LOGIN_ARCO_SAS_PAGE_REDIRECT_APP=https://app.portalsaseducacao.com.br/entrar/?appendOpaqueToken=true&redirect=https://account.educacross.com.br/sas/app?opaquetoken={{PARTNER_API_OPAQUE_TOKEN}}
ENV VITE_APP_LOGIN_ARCO_SAS_PAGE=https://app.portalsaseducacao.com.br
ENV VITE_APP_LOGIN_ARCO_COC_PAGE=https://app.coc.com.br
ENV VITE_APP_LOGIN_ARCO_COC_PAGE_REDIRECT=https://jornada.coc.com.br/entrar/?appendOpaqueToken=true&redirect=https://account.educacross.com.br/coc?opaquetoken={{PARTNER_API_OPAQUE_TOKEN}}
ENV VITE_APP_LOGIN_SAS_PAGE_REDIRECT=https://portalsaseducacao.com.br/login?appendToken=true&redirect=https://account.educacross.com.br/sas/login
ENV VITE_APP_LOGIN_SAS_PAGE_REDIRECT_APP=https://portalsaseducacao.com.br/login?appendToken=true&redirect=https://account.educacross.com.br/sas/login/app
ENV VITE_APP_WEBGL=5DE7A6BE-B5E0-4EDE-BB71-FE7EB743D4D4

# install and cache app dependencies
COPY package*.json ./

RUN npm ci

# add app
COPY . .

# generate build
RUN npm run build

# production environment
FROM nginx:alpine as production-stage

# Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
