FROM node:22-alpine as build-stage

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Increase Node memory limit for Vite builds
ENV NODE_OPTIONS=--max-old-space-size=4096

ENV VITE_APP_BASE_URL_API=https://apimanager.educacross.com.br/
ENV VITE_APP_BLOB_IMAGE=https://blob.educacross.com.br/
ENV VITE_APP_BLOB=https://blob.educacross.com.br/
ENV VITE_APP_DEEPLINK_URL=https://link.horadamatematica.com.br/
ENV VITE_APP_GOOGLE_CLIENT_ID=824777903381-oko0t2danlin33a8manp3l95i33c9qgg
ENV VITE_APP_MISSION_SUGGEST_URL=https://prod.empatie.net/
ENV VITE_APP_WEBGL_PLAY_LINK=https://account.horadamatematica.com.br/jogar
ENV VITE_APP_WHITELABEL=seduc
ENV VITE_APP_REDIRECT_URI_MICROSOFT=https://account.horadamatematica.com.br
ENV VITE_APP_WEBGL=A0CF6B63-3DA5-4B39-A016-88C4A377C76A

# install and cache app dependencies
COPY package*.json ./

RUN npm ci

# add app
COPY . .

# generate build
RUN npm run build

# production environment
FROM nginx:alpine as production-stage

# Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
