FROM node:22-alpine as build-stage

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Increase Node memory limit for Vite builds
ENV NODE_OPTIONS=--max-old-space-size=4096

ENV VITE_APP_BASE_URL_API=https://apimanager.educacross.com.br/
ENV VITE_APP_BLOB_IMAGE=https://blob.educacross.com.br/
ENV VITE_APP_BLOB=https://blob.educacross.com.br/
ENV VITE_APP_DEEPLINK_URL=https://somosplay.com.br/
ENV VITE_APP_MISSION_SUGGEST_URL=https://prod.empatie.net/
ENV VITE_APP_WEBGL_PLAY_LINK=https://somosplay.com.br/jogar
ENV VITE_APP_WHITELABEL=somosplay
ENV VITE_APP_LOGIN_URL=https://somosplay.com.br/somosplay
ENV VITE_APP_PLURALL_LINK=https://sso.plurall.net/
ENV VITE_APP_PLURALL_REDIRECT=https://somosplay.com.br/somosplay
ENV VITE_APP_PLURALL_CLIENT_ID=NjhmMmI0YTk3NmMzZTkx
ENV VITE_APP_LOGIN_PLURALL_PAGE=https://login.plurall.net/
ENV VITE_APP_WEBGL=D0A78263-861C-4AA3-8148-EF51360CC197

# install and cache app dependencies
COPY package*.json ./

RUN npm ci

# add app
COPY . .

# generate build
RUN npm run build

# production environment
FROM nginx:alpine as production-stage

# Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
