export const ModulesEnum = {
  CustomMissions: 1,
  SchoolMissions: 1,
  Islands: 2,
  Reports: 3,
  HighFive: 6,
  SpecialMissions: 7,
  TTS: 8,
  BookMissions: 9,
  EducacrossMissions: 10,
  EducationSystems: 11,
  CardReport: 12,
  SuggestGuide: 13,
  Events: 14,
  Evaluations: 15,
  StudentTraining: 16,
  SuperChallenge: 17,
  ReadingFluency: 18,
  BookLibrary: 19,
  StudentEvidence: 3,
  InclusionGuide: 20,
  SchoolMissionsAchievementRanking: 1,
  IslandsAchievementRanking: 2,
  EducationSystemsAchievementRanking: 11,
  CustomMissionsPlus: 22,
  NarrativeComplexity: 23,
}
