export const percentilePerformance = [
  {
    id: 1,
    text: 'Baixa probabilidade de baixa performance ≥ p26',
    label: 'BAIXA',
    variant: 'legend-advanced',
    textClass: 'text-legend-advanced',
    rule: value => value === 1,
    layout: 'badge',
    background: 'bg-light-legend-advanced',
    icon: 'sentiment_satisfied',
    key: 'proficient',
    studentKey: 'studentsProficient',
  },
  {
    id: 2,
    text: 'Média probabilidade de baixa performance ≥ p11',
    label: 'MÉDIA',
    variant: 'legend-basic',
    textClass: 'text-legend-basic',
    rule: value => value === 2,
    layout: 'badge',
    background: 'bg-light-legend-basic',
    icon: 'sentiment_very_satisfied',
    key: 'advenced',
    studentKey: 'studentsAdvenced',
  },
  {
    id: 3,
    text: 'Alta probabilidade de baixa performance < p11',
    label: 'ALTA',
    variant: 'legend-below-basic',
    textClass: 'text-legend-below-basic',
    rule: value => value === 3,
    layout: 'badge',
    background: 'bg-light-legend-below-basic',
    icon: 'sentiment_dissatisfied',
    key: 'belowBasic',
    studentKey: 'studentsBelowBasic',
  },
]
