export const percentileNarrativeComplexity = [
  {
    id: 3,
    text: 'Acima do esperado ≥ p76',
    variant: 'legend-advanced',
    textClass: 'text-legend-advanced',
    rule: value => value === 3,
    layout: 'badge',
    background: 'bg-light-legend-advanced',
    icon: 'sentiment_excited',
    key: 'aboveExpectations',
    studentKey: 'studentsAboveExpectations',
    label: 'Acima do esperado',
  },
  {
    id: 2,
    text: 'Dentro do esperado ≥ p26',
    variant: 'legend-proficient',
    textClass: 'text-legend-proficient',
    rule: value => value === 2,
    layout: 'badge',
    background: 'bg-light-legend-proficient',
    icon: 'sentiment_satisfied',
    key: 'withinExpectations',
    studentKey: 'studentsWithinExpectations',
    label: 'Dentro do esperado',
  },
  {
    id: 1,
    text: 'Abaixo do esperado < p26',
    variant: 'legend-below-basic',
    textClass: 'text-legend-below-basic',
    rule: value => value === 1,
    layout: 'badge',
    background: 'bg-light-legend-below-basic',
    icon: 'sentiment_dissatisfied',
    key: 'belowExpectations',
    studentKey: 'studentsBelowExpectations',
    label: 'Abaixo do esperado',
  },
]

export const percentileNarrativeComplexityLegend = {
  text: 'Percentil de Complexidade Narrativa',
  enum: percentileNarrativeComplexity,
}

export const percentileNarrativeComplexityWithNotCompleted = [
  ...percentileNarrativeComplexity,
  {
    id: 0,
    label: 'Não realizada',
    variant: 'legend-not-completed',
    textClass: 'text-legend-not-completed',
    rule: value => value === 0,
    layout: 'badge',
    background: 'bg-light-legend-not-completed',
    icon: 'no_accounts',
    key: 'notStart',
    studentKey: 'studentsNotStart',
  },
  {
    id: 5,
    label: 'Problemas identificados',
    variant: 'pink',
    textClass: 'text-pink',
    rule: value => value === 5,
    layout: 'badge',
    background: 'bg-light-pink',
    icon: 'gpp_maybe',
    key: 'error',
    studentKey: 'studentsError',
  },
]
