export const PERMISSION = {
  GENERAL: {
    ACCOUNT: 'Account',
    EDUCACROSS: 'Educacross',
    SUPPORT_MATERIALS: 'SupportMaterials',
    MANAGE_CLASSES: 'ManageClasses',
    MANAGE_TEACHERS: 'ManageTeachers',
    MANAGE_STUDENTS: 'ManageStudents',
    MANAGE_COORDINATORS: 'ManageCoordinators',
    MANAGE_MANAGERS: 'ManageManagers',
    MIGRATE_CLASS_STUDENTS: 'MigrateClassStudents',
    CHANGE_INSTITUTION_LOGO: 'ChangeInstitutionLogo',
    PDF: 'PDF',
    TEACHER: 'Teacher',
    AUDITOR: 'Auditor',
    SECRETARIAT: 'Secretariat',
    STUDENT: 'Student',
    GROUPS: 'ClassGroups',
    ADMIN: 'Admin',
    RANKING_CONQUEST: 'RankingConquest',
    ABILITY_REPORT: 'AbilityReport',
    STUDENT_EVIDENCE: 'StudentEvidence',
    MANAGE_INSTITUTIONS: 'ManageInstitutions',
    EDUCATION_SYSTEM_REPORT: 'EducationSystemReport',
    NETWORK_MANAGER: 'NetworkManager',
    NETWORK_MANAGER_PERFORMANCE_REPORT: 'NetworkManagerPerformanceReport',
    BETA_FEATURES: 'BetaFeature',
    TRANSFER_STUDENTS: 'TransferStudents',
    MODULE_MANAGEMENT: 'ModuleManagement',
    TRANSLATE: 'Translate',
    CLASS_GROUP: 'ClassGroup',
    LANGUAGE_EN: 'en',
    LANGUAGE_PTBR: 'ptbr',
    LANGUAGE_ES: 'es',
    IDIOM: 'Idiom',
    INTEGRATOR: 'Integrator',
    SOCIO_EMOTIONAL: 'SocioEmotional',
    MANAGER: 'Manager',
  },
  MODULE: {
    SCHOOL_MISSIONS: 'SchoolMissions',
    CUSTOM_MISSIONS_PLUS: 'CustomMissionsPlus', // AGUARDANDO BACK
    CUSTOM_MISSIONS: 'CustomMissions',
    ISLANDS: 'Islands',
    EXPLORE: 'Explore',
    MATH_ISLANDS: 'MathIslands',
    MATH_ISLANDS_IN_ENGLISH: 'MathIslandsInEnglish',
    HIGH_FIVE: 'HighFive',
    SPECIAL_MISSIONS: 'SpecialMissions',
    BOOK_MISSIONS: 'BookMissions',
    EDUCACROSS_MISSIONS: 'EducacrossMissions',
    EDUCATION_SYSTEMS: 'EducationSystems',
    CARD_REPORT: 'CardReport',
    SUGGEST_GUIDE: 'SuggestGuide',
    TTS: 'TTS',
    // === novos ===
    REPORTS: 'Reports',
    EVENTS: 'Events',
    EVALUATIONS: 'Evaluations', // mudar para modulos
    READINGFLUENCY: 'ReadingFluency',
    READING_FLUENCY_EVALUATION: 'ReadingFluencyEvaluation',
    READING_EXPEDITION: 'ReadingExpedition',
    BOOKLIBRARY: 'BookLibrary',
    STUDENT_TRAINING: 'StudentTraining',
    SUPER_CHALLENGE: 'SuperChallenge',
    INCLUSION_GUIDE: 'InclusionGuide',
    NARRATIVECOMPLEXITY: 'NarrativeComplexity',
    EVOLUCIIONAL_SIMULATIONS: 'EvolucionalSimulations',
    // rankings
    SCHOOL_MISSIONS_ACHIEVEMENT_RANKING: 'SchoolMissionsAchievementRanking',
    ISLANDS_ACHIEVEMENT_RANKING: 'IslandsAchievementRanking',
    EDUCATION_SYSTEMS_ACHIEVEMENT_RANKING: 'EducationSystemsAchievementRanking',
    WRITING_STAGES: 'WritingStages',
    MEET_VIDEOS: 'EducatecaVideo',
    MEET_SONGS: 'EducatecaMusic',
    MEET_KARAOKE: 'EducatecaKaraoke',
    SHARED_MISSIONS: 'SharedMissions',
  },
}

export const ACTION = {
  DISABLED: 'disabled',
  READ: 'read',
  CREATE: 'create',
  UPDATE: 'update',
  DELETE: 'delete',
}
